import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"


[font]
size = 12

[font.normal]
family = "MesloLGS NF"

[window]
opacity = 0.98
startup_mode = "Windowed"

[window.padding]
x = 12
y = 12